# file      : buildfile
# license   : Apache License 2.0; see accompanying LICENSE file

./: {*/ -build/} doc{INSTALL README} legal{LICENSE} manifest

# Don't install tests or the INSTALL file.
#
tests/:          install = false
doc{INSTALL}@./: install = false
