# file      : tests/net-accessor/buildfile
# license   : Apache License 2.0; see accompanying LICENSE file

import libs = libxerces-c%lib{xerces-c}

exe{driver}: {hxx cxx}{*} $libs testscript

# Disable MSVC warnings that pop up with /W3.
#
if ($cxx.class == 'msvc')
  cxx.coptions += /wd4267 /wd4305
