# file      : tests/sax2-print/buildfile
# license   : Apache License 2.0; see accompanying LICENSE file

import libs = libxerces-c%lib{xerces-c}

exe{driver}: SAX2Print/{hxx cxx}{*} $libs testscript
