# file      : tests/psvi-writer/buildfile
# license   : Apache License 2.0; see accompanying LICENSE file

import libs = libxerces-c%lib{xerces-c}

exe{driver}: PSVIWriter/{hxx cxx}{*} $libs testscript

switch $cxx.class
{
  case 'gcc'
  {
    # Disable warnings that pop up with -Wall -Wextra. Upstream doesn't seem
    # to care about these and it is not easy to disable specific warnings in a
    # way that works across compilers/version (some -Wno-* options are only
    # recognized in newer versions).
    #
    cxx.coptions += -Wno-all -Wno-extra
  }
  case 'msvc'
  {
    # Disable warnings that pop up with /W3.
    #
    cxx.coptions += /wd4267
  }
}
